version: '3.7'
services:

  # Power Rankings Redis Service
  necrolab-power-rankings-redis:
    image: redis:5.0.4-alpine
    container_name: necrolab-power-rankings-redis
    restart: unless-stopped
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server /etc/power_rankings.conf"] # This disables persistence
    ports:
      - "6380:6380"
    environment:
      SERVICE_NAME: necrolab-power-rankings-redis
      SERVICE_TAGS: production
    volumes:
      - ../../configurations/redis/power_rankings.conf:/etc/power_rankings.conf
      - redis-power-rankings-tmp:/tmp/redis/power_rankings
    networks:
      - necrolab-network

  # Daily Rankings Redis Service
  necrolab-daily-rankings-redis:
    image: redis:5.0.4-alpine
    container_name: necrolab-daily-rankings-redis
    restart: unless-stopped
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server /etc/daily_rankings.conf"] # This disables persistence
    ports:
      - "6381:6381"
    environment:
      SERVICE_NAME: necrolab-daily-rankings-redis
      SERVICE_TAGS: production
    volumes:
      - ../../configurations/redis/daily_rankings.conf:/etc/daily_rankings.conf
      - redis-daily-rankings-tmp:/tmp/redis/daily_rankings
    networks:
      - necrolab-network

  # Postgres Service
  necrolab-db:
    image: postgres:11.2-alpine
    container_name: necrolab-db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SERVICE_NAME=necrolab-db
      - SERVICE_TAGS=production
    volumes:
      - necrolab-db-data:/var/lib/postgresql/data
      - necrolab-db-tmp:/run
    networks:
      - necrolab-network
      
  # Nginx Service
  necrolab-webserver:
    image: nginx:alpine
    container_name: necrolab-webserver
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_SERVER_NAME=beta.necrolab.com
      - NGINX_SSL_CRT_FILE_NAME=beta.necrolab.com.crt
      - NGINX_SSL_KEY_FILE_NAME=beta.necrolab.com.key
    entrypoint: /var/run/entrypoint.sh
    volumes:
      - ../../configurations/nginx/entrypoint.sh:/var/run/entrypoint.sh:rw
      - ../../../:/var/www/html
      - ../../configurations/nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl_keys/:/etc/nginx/ssl/
      - necrolab-app-tmp:/tmp
    networks:
      - necrolab-network
  
  # PHP Web Service
  necrolab-app:
    image: necrolab-app-production:1.0
    container_name: necrolab-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: necrolab-app
      SERVICE_TAGS: production
    working_dir: /var/www/html
    volumes:
      - ../../../:/var/www/html
      - ../../configurations/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      #- ../../configurations/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - necrolab-app-tmp:/tmp
      - necrolab-db-tmp:/run
    networks:
      - necrolab-network
    depends_on:
      - necrolab-webserver
      - necrolab-db

  # Management Service
  necrolab-management:
    image: necrolab-management:1.0
    container_name: necrolab-management
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: necrolab-management
      SERVICE_TAGS: production
    volumes:
      - ../../../:/var/www
      - necrolab-db-tmp:/run
      - redis-power-rankings-tmp:/tmp/redis/power_rankings
      - redis-daily-rankings-tmp:/tmp/redis/daily_rankings
    networks:
      - necrolab-network
    depends_on:
      - necrolab-db
      - necrolab-power-rankings-redis
      - necrolab-daily-rankings-redis
      
  # Cron Service
  necrolab-cron:
    image: necrolab-app-cron:1.0
    container_name: necrolab-cron
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: necrolab-app-cron
      SERVICE_TAGS: production
    volumes:
      - ../../../:/var/www
      - necrolab-db-tmp:/run
    networks:
      - necrolab-network
    depends_on:
      - necrolab-db
      
  # Leaderboards Queue Worker
  necrolab-leaderboards-queue-worker:
    image: necrolab-queue-worker:1.0
    container_name: necrolab-leaderboards-queue-worker
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: necrolab-leaderboards-queue-worker
      SERVICE_TAGS: production
    volumes:
      - ../../../:/var/www
      - ../../configurations/supervisor/supervisord.conf:/etc/supervisord.conf
      - ../../configurations/supervisor/leaderboards.ini:/etc/supervisor.d/leaderboards.ini
      - necrolab-db-tmp:/run
    networks:
      - necrolab-network
    depends_on:
      - necrolab-db

  # Power Rankings Queue Worker
  necrolab-power-rankings-queue-worker:
    image: necrolab-queue-worker:1.0
    container_name: necrolab-power-rankings-queue-worker
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: necrolab-power-rankings-queue-worker
      SERVICE_TAGS: production
    volumes:
      - ../../../:/var/www
      - ../../configurations/supervisor/supervisord.conf:/etc/supervisord.conf
      - ../../configurations/supervisor/rankings_power.ini:/etc/supervisor.d/rankings_power.ini
      - ../../configurations/php/docker-php-ext-phpredis.ini:/usr/local/etc/php/conf.d/docker-php-ext-phpredis.ini
      - necrolab-db-tmp:/run
      - redis-power-rankings-tmp:/tmp/redis/power_rankings
    networks:
      - necrolab-network
    depends_on:
      - necrolab-power-rankings-redis
      - necrolab-db
    
  # Daily Rankings Queue Worker
  necrolab-daily-rankings-queue-worker:
    image: necrolab-queue-worker:1.0
    container_name: necrolab-daily-rankings-queue-worker
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: necrolab-daily-rankings-queue-worker
      SERVICE_TAGS: production
    volumes:
      - ../../../:/var/www
      - ../../configurations/supervisor/supervisord.conf:/etc/supervisord.conf
      - ../../configurations/supervisor/rankings_daily.ini:/etc/supervisor.d/rankings_daily.ini
      - ../../configurations/php/docker-php-ext-phpredis.ini:/usr/local/etc/php/conf.d/docker-php-ext-phpredis.ini
      - necrolab-db-tmp:/run
      - redis-daily-rankings-tmp:/tmp/redis/daily_rankings
    networks:
      - necrolab-network
    depends_on:
      - necrolab-daily-rankings-redis
      - necrolab-db

  # Replays Queue Worker
  necrolab-replays-queue-worker:
    image: necrolab-queue-worker:1.0
    container_name: necrolab-replays-queue-worker
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: necrolab-replays-queue-worker
      SERVICE_TAGS: production
    volumes:
      - ../../../:/var/www
      - ../../configurations/supervisor/supervisord.conf:/etc/supervisord.conf
      - ../../configurations/supervisor/replays.ini:/etc/supervisor.d/replays.ini
      - necrolab-db-tmp:/run
    networks:
      - necrolab-network
    depends_on:
      - necrolab-db

  # Players Queue Worker
  necrolab-players-queue-worker:
    image: necrolab-queue-worker:1.0
    container_name: necrolab-players-queue-worker
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: necrolab-players-queue-worker
      SERVICE_TAGS: production
    volumes:
      - ../../../:/var/www
      - ../../configurations/supervisor/supervisord.conf:/etc/supervisord.conf
      - ../../configurations/supervisor/players.ini:/etc/supervisor.d/players.ini
      - necrolab-db-tmp:/run
    networks:
      - necrolab-network
    depends_on:
      - necrolab-db

  # Dates Queue Worker
  necrolab-dates-queue-worker:
    image: necrolab-queue-worker:1.0
    container_name: necrolab-dates-queue-worker
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: necrolab-dates-queue-worker
      SERVICE_TAGS: production
    volumes:
      - ../../../:/var/www
      - ../../configurations/supervisor/supervisord.conf:/etc/supervisord.conf
      - ../../configurations/supervisor/dates.ini:/etc/supervisor.d/dates.ini
      - necrolab-db-tmp:/run
    networks:
      - necrolab-network
    depends_on:
      - necrolab-db

#Docker Networks
networks:
  necrolab-network:
    driver: bridge

#Volumes
volumes:
  necrolab-db-data:
    driver: local
  redis-power-rankings-tmp:
    driver: local
  redis-daily-rankings-tmp:
    driver: local
  necrolab-app-tmp:
    driver: local
  necrolab-db-tmp:
    driver: local
